import {superdeskApi} from '../../../superdeskApi';

// @ts-ignore
import * as iconFont from 'superdesk-ui-framework/app/styles/_icon-font.scss';

export interface IIcon {
    name: string;
    label: string;
}

export function getIcons(): Array<IIcon> {
    return iconFont.icon
        .split(', ')
        .sort()
        .map((icon) => ({
            name: icon,
            label: getIconNameTranslated(icon),
        }));
}

function getIconNameTranslated(name: string): string {
    const {gettext} = superdeskApi.localization;

    /* eslint-disable quote-props */
    const translatedIconNameMap = {
        'add-gallery': gettext('Add Gallery'),
        'add-image': gettext('Add Image'),
        'adjust': gettext('Adjust'),
        'align-center': gettext('Align Center'),
        'align-justify': gettext('Align Justify'),
        'align-left': gettext('Align Left'),
        'align-right': gettext('Align Right'),
        'amp': gettext('AMP'),
        'analytics': gettext('Analytics'),
        'archive': gettext('Archive'),
        'arrow-left': gettext('Arrow Left'),
        'arrow-right': gettext('Arrow Right'),
        'arrow-small': gettext('Arrow Small'),
        'ascending': gettext('Ascending'),
        'assign': gettext('Assign'),
        'attachment': gettext('Attachment'),
        'attachment-large': gettext('Attachment Large'),
        'audio': gettext('Audio'),
        'backward-thin': gettext('Backward Thin'),
        'ban-circle': gettext('Ban Circle'),
        'bell': gettext('Bell'),
        'bold': gettext('Bold'),
        'broadcast': gettext('Broadcast'),
        'broadcast-create': gettext('Broadcast Create'),
        'business': gettext('Business'),
        'calendar': gettext('Calendar'),
        'calendar-list': gettext('Calendar List'),
        'chevron-down-thin': gettext('Chevron Down Thin'),
        'chevron-left-thin': gettext('Chevron Left Thin'),
        'chevron-right-thin': gettext('Chevron Right Thin'),
        'chevron-up-thin': gettext('Chevron Up Thin'),
        'clear-all': gettext('Clear All'),
        'clear-format': gettext('Clear Format'),
        'close-small': gettext('Close Small'),
        'close-thick': gettext('Close Thick'),
        'code': gettext('Code'),
        'collapse': gettext('Collapse'),
        'comment': gettext('Comment'),
        'composite': gettext('Composite'),
        'copy': gettext('Copy'),
        'crop': gettext('Crop'),
        'cut': gettext('Cut'),
        'descending': gettext('Descending'),
        'dots': gettext('Dots'),
        'dots-vertical': gettext('Dots Vertical'),
        'download': gettext('Download'),
        'download-alt': gettext('Download Alternate'),
        'edit-line': gettext('Edit Line'),
        'envelope': gettext('Envelope'),
        'event': gettext('Event'),
        'exclamation-sign': gettext('Exclamation Sign'),
        'expand': gettext('Expand'),
        'expand-thin': gettext('Expand Thin'),
        'external': gettext('External'),
        'eye-open': gettext('Eye Open'),
        'facebook': gettext('Facebook'),
        'facebook-circle': gettext('Facebook Circle'),
        'fast_forward': gettext('Fast Forward'),
        'fast_rewind': gettext('Fast Rewind'),
        'fetch-as': gettext('Fetch As'),
        'file': gettext('File'),
        'filter-large': gettext('Filter Large'),
        'flip-horizontal': gettext('Flip Horizontal'),
        'flip-vertical': gettext('Flip Vertical'),
        'folder-close': gettext('Folder Close'),
        'folder-open': gettext('Folder Open'),
        'font': gettext('Font'),
        'forward-thin': gettext('Forward Thin'),
        'fullscreen': gettext('Fullscreen'),
        'globe': gettext('Globe'),
        'graphic': gettext('Graphic'),
        'grid-view': gettext('Grid View'),
        'grid-view-large': gettext('Grid View Large'),
        'heading-1': gettext('Heading 1'),
        'heading-2': gettext('Heading 2'),
        'heading-3': gettext('Heading 3'),
        'heading-4': gettext('Heading 4'),
        'heading-5': gettext('Heading 5'),
        'heading-6': gettext('Heading 6'),
        'heart': gettext('Heart'),
        'help-large': gettext('Help Large'),
        'highlight-package': gettext('Highlight Package'),
        'home': gettext('Home'),
        'indent-left': gettext('Indent Left'),
        'indent-right': gettext('Indent Right'),
        'info-large': gettext('Info Large'),
        'info-sign': gettext('Info Sign'),
        'ingest': gettext('Ingest'),
        'instagram': gettext('Instagram'),
        'italic': gettext('Italic'),
        'kanban-view': gettext('Kanban View'),
        'kill': gettext('Kill'),
        'link': gettext('Link'),
        'linked-in': gettext('LinkedIn'),
        'linked-in-circle': gettext('LinkedIn Circle'),
        'list-alt': gettext('List Alternate'),
        'list-menu': gettext('List Menu'),
        'list-plus': gettext('List Plus'),
        'list-view': gettext('List View'),
        'lock': gettext('Lock'),
        'map-marker': gettext('Map Marker'),
        'minus-sign': gettext('Minus Sign'),
        'minus-small': gettext('Minus Small'),
        'mobile': gettext('Mobile'),
        'move': gettext('Move'),
        'multi-star': gettext('Multi Start'),
        'multiedit': gettext('Multi Edit'),
        'new-doc': gettext('New Document'),
        'ok': gettext('Okay'),
        'ordered-list': gettext('Ordered List'),
        'package-create': gettext('Package Create'),
        'package-plus': gettext('Package Plus'),
        'paragraph': gettext('Paragraph'),
        'paste': gettext('Paste'),
        'pause': gettext('Pause'),
        'paywall': gettext('Paywall'),
        'pencil': gettext('Pencil'),
        'phone': gettext('Phone'),
        'photo': gettext('Photo'),
        'pick': gettext('Pick'),
        'picture': gettext('Picture'),
        'pin': gettext('Pin'),
        'play': gettext('Play'),
        'plus-large': gettext('Plus Large'),
        'plus-sign': gettext('Plus Sign'),
        'plus-small': gettext('Plus Small'),
        'post': gettext('Post'),
        'preformatted': gettext('Preformatted'),
        'preview-mode': gettext('Preview Mode'),
        'print': gettext('Print'),
        'question-sign': gettext('Question Sign'),
        'quote': gettext('Quote'),
        'random': gettext('Random'),
        'recurring': gettext('Recurring'),
        'redo': gettext('Redo'),
        'refresh': gettext('Refresh'),
        'remove-sign': gettext('Remove Sign'),
        'repeat': gettext('Repeat'),
        'retweet': gettext('Retweet'),
        'revert': gettext('Revert'),
        'rotate-left': gettext('Rotate Left'),
        'rotate-right': gettext('Rotate Right'),
        'search': gettext('Search'),
        'settings': gettext('Settings'),
        'share-alt': gettext('Share Alternate'),
        'signal': gettext('Signal'),
        'skip_next': gettext('Skip Next'),
        'skip_previous': gettext('Skip Previous'),
        'slideshow': gettext('Slideshow'),
        'star': gettext('Star'),
        'star-empty': gettext('Star Empty'),
        'stop': gettext('Stop'),
        'stream': gettext('Stream'),
        'strikethrough': gettext('Strikethrough'),
        'subscript': gettext('Subscript'),
        'suggestion': gettext('Suggestion'),
        'superscript': gettext('Superscript'),
        'switches': gettext('Switches'),
        'table': gettext('Table'),
        'takes-package': gettext('Takes Package'),
        'tasks': gettext('Tasks'),
        'text': gettext('Text'),
        'text-format': gettext('Text Format'),
        'th': gettext('Table Header'),
        'th-large': gettext('Table Header Large'),
        'th-list': gettext('Table Header List'),
        'time': gettext('Time'),
        'to-lowercase': gettext('To Lowercase'),
        'to-uppercase': gettext('To Uppercase'),
        'trash': gettext('Trash'),
        'twitter': gettext('Twitter'),
        'twitter-circle': gettext('Twitter Circle'),
        'underline': gettext('Underline'),
        'undo': gettext('Undo'),
        'unlocked': gettext('Unlocked'),
        'unordered-list': gettext('Unordered List'),
        'unspike': gettext('Unspike'),
        'upload': gettext('Upload'),
        'user': gettext('User'),
        'video': gettext('Video'),
        'warning-sign': gettext('Warning Sign'),
        'zoom-in': gettext('Zoom In'),
        'zoom-out': gettext('Zoom Out'),
    };
    /* eslint-enable quote-props */

    return translatedIconNameMap[name] ?? name;
}
