version: "3.8"

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        environment:
            - discovery.type=single-node
        networks:
            - e2e
        tmpfs:
            - /usr/share/elasticsearch/data

    redis:
        image: redis:alpine
        networks:
            - e2e

    mongo:
        image: mongo:4
        networks:
            - e2e
        tmpfs:
            - /data/db

    server:
        build: 
            context: ../
            dockerfile: e2e/server/Dockerfile
        ports:
            - "5000:5000"
        networks:
            - e2e
        depends_on:
            - redis
            - mongo
            - elastic
        environment:
            - WEB_CONCURRENCY=2
            - WEBPACK_MANIFEST_PATH=/opt/client-dist/manifest.json
            - MONGO_URI=mongodb://mongo/superdesk
            - ARCHIVED_MONGO_URI=mongodb://mongo/superdesk
            - CONTENTAPI_MONGO_URI=mongodb://mongo/superdesk_capi
            - PUBLICAPI_MONGO_URI=mongodb://mongo/superdesk_papi
            - LEGAL_ARCHIVE_URI=mongodb://mongo/superdesk_legal
            - ARCHIVED_URI=mongodb://mongo/superdesk_archive
            - ELASTICSEARCH_URL=http://elastic:9200
            - ELASTICSEARCH_INDEX=superdesk_e2e
            - CELERY_BROKER_URL=redis://redis:6379/1
            - REDIS_URL=redis://redis:6379/1
            - DEFAULT_TIMEZONE=Europe/Prague
            - SECRET_KEY=e2e

networks:
    e2e:
        driver: bridge
