import moment from 'moment-timezone';

export const TIMEZONE = moment.tz.guess();

/**
 * Calculates and returns the starting moment of the next week.
 * The week starts on Sunday as per the configuration in this method.
 *
 * @return {moment.Moment} A moment object representing the beginning of the next week (Sunday at 00:00:00, 000ms).
 */
export function getStartOfNextWeek(): moment.Moment {
    const startOfWeek = 0;
    let current = (moment()).set({
        hour: 0,
        minute: 0,
        second: 0,
        millisecond: 0,
    });
    let weekDay = current.isoWeekday();

    // If the day is Sunday, then change this to 0
    // This is the same format the startOfWeek config uses
    weekDay = weekDay === 7 ? 0 : weekDay;

    const diff = weekDay < startOfWeek ?
        // If the weekDay is before the start of the week,
        // then jump forward the difference of the two
        startOfWeek - weekDay :

        // Otherwise jump forward the remaining amount till next week
        7 - weekDay + startOfWeek;

    return current.add(diff, 'd');
}

export function getSafeNextWeek(): moment.Moment {
    const nextWeek = getStartOfNextWeek();
    const tomorrow = moment()
        .set({
            hour: 0,
            minute: 0,
            second: 0,
            millisecond: 0,
        })
        .add(1, 'd');

    // Keep next-week fixtures distinct from tomorrow for weekday-sensitive search specs.
    return nextWeek.isSame(tomorrow, 'day') ? nextWeek.add(1, 'd') : nextWeek;
}

/**
 * An object containing methods to compute specific date strings in the format 'YYYY-MM-DD'.
 *
 * Properties:
 * - today: Returns the date string for today, setting the time to 00:00.
 * - yesterday: Returns the date string for yesterday, setting the time to 00:00.
 * - tomorrow: Returns the date string for tomorrow, setting the time to 00:00.
 * - next_week: Returns the date string for the start of the next week.
 *
 * Note: All dates are formatted using the 'YYYY-MM-DD' format.
 */
export const getDateStringFor = {
    today: () => moment()// .utc()
        .set({hour: 0})
        .format('YYYY-MM-DD'),
    yesterday: () => moment()// .utc()
        .set({hour: 0})
        .subtract(1, 'd')
        .format('YYYY-MM-DD'),
    tomorrow: () => moment()// .utc()
        .set({hour: 0})
        .add(1, 'd')
        .format('YYYY-MM-DD'),
    next_week: () => getStartOfNextWeek()
        .format('YYYY-MM-DD'),
    safe_next_week: () => getSafeNextWeek()
        .format('YYYY-MM-DD'),
};

/**
 * Generates a formatted time string for a specified hour in UTC timezone.
 *
 * @param {number} hour - The hour (0-23) for which the time string should be generated.
 * @return {string} The time string formatted as 'THH:00:00+0000'.
 */
export function getTimeStringForHour(hour: number): string {
    return moment()// .utc()
        .set({hour: hour})
        .format('THH:00:00+0000');
}

/**
 * An object that maps hour values (in 24-hour format) to their corresponding time strings.
 *
 * The keys represent the hour of the day, starting from 0 (midnight) to other specified hours,
 * and the values are generated by the getTimeStringForHour function, which returns the
 * formatted time string for the given hour.
 *
 * @type {Object<number, string>}
 */
export const TIME_STRINGS = {
    0: getTimeStringForHour(0),
    1: getTimeStringForHour(1),
    2: getTimeStringForHour(2),
    3: getTimeStringForHour(3),
    4: getTimeStringForHour(4),
};
