import pytz
import itertools

from bson import ObjectId
from typing import Any, AsyncGenerator
from datetime import datetime, timedelta
from apps.auth import get_user, get_user_id

from superdesk import get_resource_service
from superdesk.errors import SuperdeskApiError
from superdesk.metadata.item import GUID_NEWSML
from superdesk.core import get_app_config, get_current_app
from superdesk.core.utils import date_to_str, generate_guid

from planning.types import (
    PLANNING_RELATED_EVENT_LINK_TYPE,
    EventResourceModel,
    PlanningRelatedEventLink,
    PlanningSchedule,
)
from planning.types.event import EmbeddedPlanning
from planning.common import WorkflowStates, get_event_max_multi_day_duration, get_max_recurrent_events
from planning.core.service import BasePlanningAsyncService
from planning.utils import get_planning_event_link_method, get_related_event_ids_for_planning

from .events_sync import sync_event_metadata_with_planning_items
from .events_utils import generate_recurring_dates, get_events_embedded_planning


class EventsAsyncService(BasePlanningAsyncService[EventResourceModel]):
    resource_name = "events"

    async def get_expired_items(
        self, expiry_datetime: datetime, spiked_events_only: bool = False
    ) -> AsyncGenerator[list[dict[str, Any]], None]:
        """Get the expired items

        Where end date is in the past
        """
        query: dict[str, Any] = {
            "query": {
                "bool": {
                    "must_not": [{"term": {"expired": True}}],
                    "filter": {"range": {"dates.end": {"lte": date_to_str(expiry_datetime)}}},
                },
            },
            "sort": [{"dates.start": "asc"}],
            "size": get_max_recurrent_events(),
        }

        if spiked_events_only:
            del query["query"]["bool"]["must_not"]
            query["query"]["bool"]["must"] = [{"term": {"state": WorkflowStates.SPIKED}}]

        total_received = 0
        total_events = -1

        while True:
            query["from"] = total_received

            results = await self.search(query)
            items = await results.to_list_raw()
            results_count = len(items)

            # If the total_events has not been set, then this is the first query
            # In which case we need to store the total hits from the search
            if total_events < 0:
                total_events = results_count

                # If the search doesn't contain any results, return here
                if total_events < 1:
                    break

            # If the last query doesn't contain any results, return here
            if results_count == 0:
                break

            total_received += results_count

            # Yield the results for iteration by the callee
            yield items

    async def create(self, docs: list[EventResourceModel]):
        """
        Extracts out the ``embedded_planning`` before saving the Event(s)
        And then uses them to synchronise/process the associated Planning item(s)
        """

        ids = await super().create(docs)

        embedded_planning_lists: list[tuple[EventResourceModel, list[EmbeddedPlanning]]] = []

        for event in docs:
            embedded_planning = get_events_embedded_planning(event)
            if len(embedded_planning):
                embedded_planning_lists.append((event.to_dict(), embedded_planning))

        if len(embedded_planning_lists):
            for event, embedded_planning in embedded_planning_lists:
                sync_event_metadata_with_planning_items(None, event, embedded_planning)

        return ids

    async def on_create(self, docs: list[EventResourceModel]) -> None:
        # events generated by recurring rules
        generated_events = []
        for event in docs:
            # generates an unique id
            if not event.guid:
                event.guid = generate_guid(type=GUID_NEWSML)
            event.id = event.guid

            if not event.language:
                try:
                    event.language = event.languages[0]
                except IndexError:
                    event.language = get_app_config("DEFAULT_LANGUAGE")

            # TODO-ASYNC: consider moving this into base service later
            event.original_creator = ObjectId(get_user_id()) or None

            # overwrite expiry date if needed
            self._overwrite_event_expiry_date(event)

            # we ignore the 'update_method' on create
            if event.update_method:
                event.update_method = None

            # remove the 'expired' flag if it is set, as no new Event can be created as expired
            if event.expired:
                event.expired = False

            self._set_planning_schedule(event)
            original_planning_item = event.planning_item

            # validate event
            self.validate_event(event)

            # If _created_externally is true, generate_recurring_events is restricted.
            if event.dates and event.dates.recurring_rule and not event.dates.recurring_rule._created_externally:
                recurring_events = self._generate_recurring_events(event)
                generated_events.extend(recurring_events)

                # Set the current Event to the first Event in the new series
                # This will make sure the ID of the Event can be used when
                # using 'event' from here on, such as when linking to a Planning item
                event = recurring_events[0]

                # And set the Planning Item from the original
                # (generate_recurring_events removes this field)
                event.planning_item = original_planning_item

            if event.state == WorkflowStates.INGESTED:
                events_history = get_resource_service("events_history")
                events_history.on_item_created([event.to_dict()])

            if original_planning_item:
                self._link_to_planning(event)
                del event["_planning_item"]

        if generated_events:
            docs.extend(generated_events)

    def validate_event(self, updated_event: EventResourceModel, original_event: EventResourceModel | None = None):
        """Validate the event

        @:param dict event: event created or updated
        """

        assert updated_event is not None

        self._validate_multiday_event_duration(updated_event)
        self._validate_dates(updated_event, original_event)
        self._validate_convert_to_recurring(updated_event, original_event)
        self._validate_template(updated_event, original_event)

        # TODO-ASYNC: migrate `sanitize_input_data` to support new models based on pydantic
        # this function below allows both Event and Planning items
        # sanitize_input_data(updates)

    def _validate_multiday_event_duration(self, event: EventResourceModel):
        """Validate that the multiday event duration is not greater than PLANNING_MAX_MULTI_DAY_DURATION

        @:param dict event: event created or updated
        """
        max_duration = get_event_max_multi_day_duration()
        if not max_duration > 0:
            return

        if not event.dates:
            return

        assert event.dates.start is not None
        assert event.dates.end is not None

        event_duration = event.dates.end - event.dates.start
        if event_duration.days > max_duration:
            raise SuperdeskApiError(message="Event duration is greater than {} days.".format(max_duration))

    def _validate_dates(self, updated_event: EventResourceModel, original_event: EventResourceModel | None = None):
        """Validate the dates

        @:param dict event:
        """
        # TODO-ASYNC: consider/check if these validations should be in the pydantic model
        event = updated_event if updated_event.dates or not original_event else original_event

        assert event.dates is not None

        start_date = event.dates.start
        end_date = event.dates.end

        if not start_date or not end_date:
            raise SuperdeskApiError(message="Event START DATE and END DATE are mandatory.")

        if end_date < start_date:
            raise SuperdeskApiError(message="END TIME should be after START TIME")

        if event.dates.recurring_rule and not event.dates.recurring_rule.until and not event.dates.recurring_rule.count:
            raise SuperdeskApiError(message="Recurring event should have an end (until or count)")

    def _validate_convert_to_recurring(
        self, updated_event: EventResourceModel, original: EventResourceModel | None = None
    ):
        """Validates if the convert to recurring action is valid.

        :param updates:
        :param original:
        :return:
        """
        if original is None:
            return

        if (
            original.lock_action == "convert_recurring"
            and updated_event.dates
            and updated_event.dates.recurring_rule is None
        ):
            raise SuperdeskApiError(message="Event recurring rules are mandatory for convert to recurring action.")

        if original.lock_action == "convert_recurring" and original.recurrence_id:
            raise SuperdeskApiError(message="Event is already converted to recurring event.")

    @staticmethod
    def _validate_template(updated_event: EventResourceModel, original_event: EventResourceModel | None = None):
        """Ensures that event template can't be changed

        :param updates: updates to event that should be saved
        :type updates: dict
        :param original: original event before update
        :type original: dict
        :return:
        """
        if original_event is None:
            return

        # we can't change `template` id
        if updated_event.template and updated_event.template != original_event.template:
            raise SuperdeskApiError.badRequestError(
                message="Request is not valid",
                payload={"template": "This value can't be changed."},
            )

    def _set_planning_schedule(self, event: EventResourceModel):
        if event.dates and event.dates.start:
            event.planning_schedule = [PlanningSchedule(scheduled=event.dates.start)]

    def _overwrite_event_expiry_date(self, event: EventResourceModel):
        if event.expiry:
            assert event.dates is not None
            assert event.dates.end is not None

            expiry_minutes = get_app_config("PLANNING_EXPIRY_MINUTES", None)
            event.expiry = event.dates.end + timedelta(minutes=expiry_minutes or 0)

    def set_recurring_mode(self, event: EventResourceModel):
        assert event.dates is not None
        assert event.dates.recurring_rule is not None

        end_repeat_mode = event.dates.recurring_rule.end_repeat_mode

        if end_repeat_mode == "count":
            event.dates.recurring_rule.until = None
        elif end_repeat_mode == "until":
            event.dates.recurring_rule.count = None

    def _reset_recurring_event_fields(self, event: EventResourceModel):
        """
        Reset fields that are not required by the new (recurring) events
        """
        fields_to_reset = ["lock_user", "lock_time", "lock_session", "lock_action"]

        for field in fields_to_reset:
            setattr(event, field, None)

    def _generate_recurring_events(
        self, event: EventResourceModel, recurrence_id: int | None = None
    ) -> list[EventResourceModel]:
        """
        Generate recurring events based on the recurrence rules of the given event.

        Args:
            event (EventResourceModel): The original event used as a template for recurrence.
            recurrence_id (int, optional): The ID of the recurrence group. Defaults to None.

        Returns:
            list[EventResourceModel]: A list of newly generated recurring events.
        """
        assert event.dates is not None

        self.set_recurring_mode(event)
        generated_events = []

        assert event.dates.start is not None
        assert event.dates.end is not None
        assert event.dates.recurring_rule is not None

        # compute the difference between start and end in the original event
        time_delta = event.dates.end - event.dates.start

        max_recurring_events = get_max_recurrent_events()
        recurring_dates = generate_recurring_dates(
            start=event.dates.start,
            tz=pytz.timezone(event.dates.tz or ""),
            **event.dates.recurring_rule.to_dict(),
        )

        # for all the dates based on the recurring rules
        # set a limit to prevent too many events to be created
        for date in itertools.islice(recurring_dates, 0, max_recurring_events):
            # prepare data for new recurring event
            new_id = generate_guid(type=GUID_NEWSML)
            recurring_event_updates = {"dates": dict(start=date, end=(date + time_delta)), "guid": new_id, "id": new_id}

            if not recurrence_id:
                recurring_event_updates["recurrence_id"] = new_id

            # reset fields not required by new events
            fields_to_reset = [
                "lock_user",
                "lock_time",
                "lock_session",
                "lock_action",
                "planning_schedule",
                "reschedule_from_schedule",
                "planning_item",
                "pubstatus",
                "reschedule_from",
            ]
            for field in fields_to_reset:
                recurring_event_updates[field] = None

            # let's finally clone the original event & update it with recurring event data
            new_event = event.model_copy(update=recurring_event_updates, deep=True)

            # set expiry date
            self._overwrite_event_expiry_date(new_event)
            self._set_planning_schedule(new_event)

            generated_events.append(new_event)

        return generated_events

    @staticmethod
    def _link_to_planning(event: EventResourceModel):
        """
        Links an Event to an existing Planning Item

        The Planning item remains locked, it is up to the client to release this lock
        after this operation is complete
        """
        # TODO-ASYNC: replace when planning service is async
        planning_service = get_resource_service("planning")
        plan_id = event.planning_item

        planning_item = planning_service.find_one(req=None, _id=plan_id)

        if not planning_item:
            raise SuperdeskApiError.badRequestError("Planning item not found")

        updates = {"related_events": planning_item.get("related_events") or []}
        event_link_method = get_planning_event_link_method()
        link_type: PLANNING_RELATED_EVENT_LINK_TYPE = (
            "primary"
            if not len(get_related_event_ids_for_planning(planning_item, "primary"))
            and event_link_method in ("one_primary", "one_primary_many_secondary")
            else "secondary"
        )
        related_planning = PlanningRelatedEventLink(_id=event.id, link_type=link_type)
        updates["related_events"].append(related_planning)

        # Add ``recurrence_id`` if the supplied Event is part of a series
        if event.recurrence_id:
            related_planning["recurrence_id"] = event.recurrence_id
            if not planning_item.get("recurrence_id") and link_type == "primary":
                updates["recurrence_id"] = event.recurrence_id

        planning_service.validate_on_update(updates, planning_item, get_user())
        planning_service.system_update(plan_id, updates, planning_item)

        app = get_current_app().as_any()
        app.on_updated_planning(updates, planning_item)
