import pytz
import itertools

from datetime import timedelta
from apps.auth import get_user_id

from superdesk.core import get_app_config
from superdesk import get_resource_service
from superdesk.core.utils import generate_guid
from superdesk.metadata.item import GUID_NEWSML

from planning.types import EventResourceModel, PlanningSchedule
from planning.common import WorkflowStates, get_max_recurrent_events
from planning.core.service import BasePlanningAsyncService

from .events_utils import generate_recurring_dates


class EventsAsyncService(BasePlanningAsyncService[EventResourceModel]):
    resource_name = "events"

    async def on_create(self, docs: list[EventResourceModel]) -> None:
        # events generated by recurring rules
        generated_events = []
        for event in docs:
            # generates an unique id
            if not event.guid:
                event.guid = generate_guid(type=GUID_NEWSML)
            event.id = event.guid

            if not event.language:
                try:
                    event.language = event.languages[0]
                except IndexError:
                    event.language = get_app_config("DEFAULT_LANGUAGE")

            # TODO-ASYNC: consider moving this into base service later
            event.original_creator = get_user_id() or None

            # overwrite expiry date if needed
            self._overwrite_event_expiry_date(event)

            # we ignore the 'update_method' on create
            if event.update_method:
                event.update_method = None

            # remove the 'expired' flag if it is set, as no new Event can be created as expired
            if event.expired:
                event.expired = None

            self._set_planning_schedule(event)
            original_planning_item = event.planning_item

            # validate event
            self.validate_event(event)

            # If _created_externally is true, generate_recurring_events is restricted.
            if event.dates.recurring_rule and not event.dates.recurring_rule._created_externally:
                recurring_events = self._generate_recurring_events(event)
                generated_events.extend(recurring_events)

                # Set the current Event to the first Event in the new series
                # This will make sure the ID of the Event can be used when
                # using 'event' from here on, such as when linking to a Planning item
                event = recurring_events[0]

                # And set the Planning Item from the original
                # (generate_recurring_events removes this field)
                event.planning_item = original_planning_item

            if event.state == WorkflowStates.INGESTED:
                events_history = get_resource_service("events_history")
                events_history.on_item_created([event])

            if original_planning_item:
                self._link_to_planning(event)
                del event["_planning_item"]

        if generated_events:
            docs.extend(generated_events)

    def _set_planning_schedule(self, event: EventResourceModel):
        if event.dates.start:
            event.planning_schedule = [PlanningSchedule(scheduled=event.dates.start)]

    def _overwrite_event_expiry_date(self, event: EventResourceModel):
        if event.expiry:
            expiry_minutes = get_app_config("PLANNING_EXPIRY_MINUTES", None)
            event.expiry = event.dates.end + timedelta(minutes=expiry_minutes or 0)

    def set_recurring_mode(self, event: EventResourceModel):
        end_repeat_mode = event.dates.recurring_rule.end_repeat_mode

        if end_repeat_mode == "count":
            event.dates.recurring_rule.until = None
        elif end_repeat_mode == "until":
            event.dates.recurring_rule.count = None

    def _reset_recurring_event_fields(self, event: EventResourceModel):
        """
        Reset fields that are not required by the new (recurring) events
        """
        fields_to_reset = ["lock_user", "lock_time", "lock_session", "lock_action"]

        for field in fields_to_reset:
            setattr(event, field, None)

    def _generate_recurring_events(
        self, event: EventResourceModel, recurrence_id: int = None
    ) -> list[EventResourceModel]:
        """
        Generate recurring events based on the recurrence rules of the given event.

        Args:
            event (EventResourceModel): The original event used as a template for recurrence.
            recurrence_id (int, optional): The ID of the recurrence group. Defaults to None.

        Returns:
            list[EventResourceModel]: A list of newly generated recurring events.
        """
        self.set_recurring_mode(event)
        generated_events = []

        # compute the difference between start and end in the original event
        time_delta = event.dates.end - event.dates.start

        max_recurring_events = get_max_recurrent_events()
        recurring_dates = generate_recurring_dates(
            start=event.dates.start,
            tz=pytz.timezone(event.dates.tz or None),
            **event.dates.recurring_rule,
        )

        # for all the dates based on the recurring rules
        # set a limit to prevent too many events to be created
        for date in itertools.islice(recurring_dates, 0, max_recurring_events):
            # prepare data for new recurring event
            new_id = generate_guid(type=GUID_NEWSML)
            recurring_event_updates = {"dates": dict(start=date, end=(date + time_delta)), "guid": new_id, "id": new_id}

            if not recurrence_id:
                recurring_event_updates["recurrence_id"] = new_id

            # reset fields not required by new events
            fields_to_reset = [
                "lock_user",
                "lock_time",
                "lock_session",
                "lock_action",
                "planning_schedule",
                "reschedule_from_schedule",
                "planning_item",
                "pubstatus",
                "reschedule_from",
            ]
            for field in fields_to_reset:
                recurring_event_updates[field] = None

            # let's finally clone the original event & update it with recurring event data
            new_event = event.model_copy(update=recurring_event_updates, deep=True)

            # set expiry date
            self._overwrite_event_expiry_date(new_event)
            self._set_planning_schedule(new_event)

            generated_events.append(new_event)

        return generated_events
