from sys import argv
from pathlib import Path

from superdesk.core.types import DefaultOperator
from superdesk.core.openapi import OpenAPISpec

from planning.types import SearchDateRange
from planning.content_api.views import event_endpoints, planning_endpoints
from planning.content_api.views.events import ContentAPIEventResponse
from planning.content_api.views.planning import ContentAPIPlanningResponse


FILE_HEADER = """# ----------------------------------------------------------------------------------
# This file has been automatically generated by the `update_capi_docs.py` script.
# DO NOT EDIT MANUALLY
# Run `python scripts/update_capi_docs.py` from `superdesk-planning/server` instead.
# ----------------------------------------------------------------------------------

"""


def update_capi_planning_spec(print_to_stdout: bool) -> None:
    spec = (
        OpenAPISpec(
            title="Content API",
            description="Combined API for managing Events and Planning items",
        )
        .add_server("http://localhost:5400/", "Development server")
        .add_tag("Events", "Event management operations")
        .add_tag("Planning", "Planning item management operations")
        .add_model(ContentAPIPlanningResponse)
        .add_model(ContentAPIEventResponse)
        .add_enum(DefaultOperator)
        .add_enum(SearchDateRange)
        .add_endpoint(event_endpoints)
        .add_endpoint(planning_endpoints)
        .remove_additional_properties_from_top_level()
    )

    # Add optional details for the ninjs3 state/end times
    # This is required as Pydantic doesn't support this spec in models
    spec.spec["components"]["schemas"]["DatesObject"]["anyOf"] = [
        {
            "oneOf": [
                {"required": "startDate", "title": "Start date & time"},
                {"required": "expectedStartDate", "title": "Start date"},
            ],
        },
        {
            "oneOf": [
                {"required": "endDate", "title": "End date & time"},
                {"required": "expectedEndDate", "title": "End date"},
            ],
        },
    ]

    spec_string = FILE_HEADER + spec.to_string("yaml")
    if print_to_stdout:
        print(spec_string)
    else:
        file_path = Path(__file__).parent.parent.joinpath("planning/static/swagger.yaml").resolve()
        with open(file_path, "w") as spec_file:
            spec_file.write(spec_string)


if __name__ == "__main__":
    update_capi_planning_spec(argv[1] == "print" if len(argv) > 1 else False)
