export const AGENDA = {
    ACTIONS: {
        ADD_OR_REPLACE_AGENDA: 'ADD_OR_REPLACE_AGENDA',
        RECEIVE_AGENDAS: 'RECEIVE_AGENDAS',
        SELECT_AGENDA: 'SELECT_AGENDA',
        REQUEST_AGENDAS: 'REQUEST_AGENDAS',
    },
    FILTER: {
        NO_AGENDA_ASSIGNED: 'NO_AGENDA_ASSIGNED',
        ALL_PLANNING: 'ALL_PLANNING',
    },
};
