export const ASSIGNMENTS = {
    ACTIONS: {
        RECEIVED_ASSIGNMENTS: 'RECEIVED_ASSIGNMENTS',
        RECEIVED_MORE_ASSIGNMENTS: 'RECEIVED_MORE_ASSIGNMENTS',
        CHANGE_LIST_SETTINGS: 'CHANGE_LIST_SETTINGS',
        SELECT_ASSIGNMENTS: 'SELECT_ASSIGNMENTS',
        DESELECT_ASSIGNMENT: 'DESELECT_ASSIGNMENT',
        PREVIEW_ASSIGNMENT: 'PREVIEW_ASSIGNMENT',
        CLOSE_PREVIEW_ASSIGNMENT: 'CLOSE_PREVIEW_ASSIGNMENT',
        SET_ASSIGNMENTS_LIST: 'SET_ASSIGNMENTS_LIST',
        ADD_TO_ASSIGNMENTS_LIST: 'ADD_TO_ASSIGNMENTS_LIST',
        DESK_CHANGE: 'DESK_CHANGE',
        OPEN_ASSIGNMENT_EDITOR: 'OPEN_ASSIGNMENT_EDITOR',
        CLOSE_ASSIGNMENT_EDITOR: 'CLOSE_ASSIGNMENT_EDITOR',
    },

    WORKFLOW_STATE: {
        ASSIGNED: 'assigned',
        IN_PROGRESS: 'in_progress',
        COMPLETED: 'completed',
        SUBMITTED: 'submitted',
        CANCELLED: 'cancelled',
    },
}
