export const ASSIGNMENTS = {
    ACTIONS: {
        RECEIVED_ASSIGNMENTS: 'RECEIVED_ASSIGNMENTS',
        RECEIVED_MORE_ASSIGNMENTS: 'RECEIVED_MORE_ASSIGNMENTS',
        CHANGE_LIST_SETTINGS: 'CHANGE_LIST_SETTINGS',
        SELECT_ASSIGNMENTS: 'SELECT_ASSIGNMENTS',
        DESELECT_ASSIGNMENT: 'DESELECT_ASSIGNMENT',
        PREVIEW_ASSIGNMENT: 'PREVIEW_ASSIGNMENT',
        CLOSE_PREVIEW_ASSIGNMENT: 'CLOSE_PREVIEW_ASSIGNMENT',
    },
}
