export const EVENTS_PLANNING = {
    ACTIONS: {
        SET_EVENTS_PLANNING_LIST: 'SET_EVENTS_PLANNING_LIST',
        ADD_EVENTS_PLANNING_LIST: 'ADD_EVENTS_PLANNING_LIST',
        CLEAR_EVENTS_PLANNING_LIST: 'CLEAR_EVENTS_PLANNING_LIST',
        SHOW_RELATED_PLANNINGS: 'SHOW_RELATED_PLANNINGS',
    },
};
