export const EVENTS_PLANNING = {
    ACTIONS: {
        SET_EVENTS_PLANNING_LIST: 'SET_EVENTS_PLANNING_LIST',
        ADD_EVENTS_PLANNING_LIST: 'ADD_EVENTS_PLANNING_LIST',
        CLEAR_EVENTS_PLANNING_LIST: 'CLEAR_EVENTS_PLANNING_LIST',
        SHOW_RELATED_PLANNINGS: 'SHOW_RELATED_PLANNINGS',
        REQUEST_EVENTS_PLANNING_LIST: 'REQUEST_EVENTS_PLANNING_LIST',
        SPIKE_EVENT: 'EVENTS_PLANNING_SPIKE_EVENT',
        UNSPIKE_EVENT: 'EVENTS_PLANNING_UNSPIKE_EVENT',
        SPIKE_PLANNING: 'EVENTS_PLANNING_SPIKE_PLANNING',
        UNSPIKE_PLANNING: 'EVENTS_PLANNING_UNSPIKE_PLANNING'
    }
};
