export const EVENTS_PLANNING = {
    ACTIONS: {
        SET_EVENTS_PLANNING_LIST: 'SET_EVENTS_PLANNING_LIST',
        ADD_EVENTS_PLANNING_LIST: 'ADD_EVENTS_PLANNING_LIST',
        CLEAR_EVENTS_PLANNING_LIST: 'CLEAR_EVENTS_PLANNING_LIST',
        SHOW_RELATED_PLANNINGS: 'SHOW_RELATED_PLANNINGS',
        RECEIVE_EVENTS_PLANNING_FILTERS: 'RECEIVE_EVENTS_PLANNING_FILTERS',
        ADD_OR_REPLACE_EVENTS_PLANNING_FILTER: 'ADD_OR_REPLACE_EVENTS_PLANNING_FILTER',
        SELECT_EVENTS_PLANNING_FILTER: 'SELECT_EVENTS_PLANNING_FILTER',
    },
    FILTER: {
        ALL_EVENTS_PLANNING: 'ALL_EVENTS_PLANNING',
    },
};
