export const LOCATIONS = {
    ACTIONS: {
        LOCATIONS_CHANGE_LIST_SETTINGS: 'LOCATIONS_CHANGE_LIST_SETTINGS',
        EDIT_LOCATION: 'EDIT_LOCATION',
        UPDATE_LOCATION: 'UPDATE_LOCATION',
        CREATE_LOCATION: 'CREATE_LOCATION',
        REMOVE_LOCATION: 'REMOVE_LOCATION',
        START_LOADING_LOCATIONS: 'START_LOADING_LOCATIONS',
        RECIEVE_LOCATIONS: 'RECIEVE_LOCATIONS',
        RECIEVE_NEW_LOCATIONS: 'RECIEVE_NEW_LOCATIONS',
        CANCEL_EDIT: 'CANCEL_EDIT_LOCATION',
        SET_SEARCH: 'SET_SEARCH_LOCATIONS',
        SET_BROWSE: 'SET_BROWSE_LOCATIONS',
    },
};