export const MAIN = {
    ACTIONS: {
        PREVIEW: 'MAIN_PREVIEW',
        OPEN_EDITOR: 'MAIN_OPEN_EDITOR',
        CLOSE_EDITOR: 'MAIN_CLOSE_EDITOR',
        FILTER: 'MAIN_FILTER',
        HISTORY: 'MAIN_HISTORY',
        CLOSE_PREVIEW: 'MAIN_CLOSE_PREVIEW',
        REQUEST: 'MAIN_REQUEST',
        CLEAR_SEARCH: 'MAIN_CLEAR_SEARCH'
    },
    FILTERS: {
        COMBINED: 'COMBINED',
        EVENTS: 'EVENTS',
        PLANNING: 'PLANNING',
    }
};
