export const MAIN = {
    ACTIONS: {
        PREVIEW: 'MAIN_PREVIEW',
        OPEN_EDITOR: 'MAIN_OPEN_EDITOR',
        CLOSE_EDITOR: 'MAIN_CLOSE_EDITOR',
        FILTER: 'MAIN_FILTER',
        HISTORY: 'MAIN_HISTORY',
        CLOSE_PREVIEW: 'MAIN_CLOSE_PREVIEW',
        REQUEST: 'MAIN_REQUEST',
        CLEAR_SEARCH: 'MAIN_CLEAR_SEARCH',
        SET_TOTAL: 'MAIN_SET_TOTAL',
        SET_UNSET_LOADING_INDICATOR: 'MAIN_SET_UNSET_LOADING_INDICATOR',

        SET_PREVIEW_ITEM: 'MAIN_SET_PREVIEW_ITEM',
        PREVIEW_LOADING_START: 'MAIN_PREVIEW_LOADING_START',
        PREVIEW_LOADING_COMPLETE: 'MAIN_PREVIEW_LOADING_COMPLETE',

        SET_EDIT_ITEM: 'MAIN_SET_EDIT_ITEM',
        EDIT_LOADING_START: 'MAIN_EDIT_LOADING_START',
        EDIT_LOADING_COMPLETE: 'MAIN_EDIT_LOADING_COMPLETE',

        SET_JUMP_INTERVAL: 'MAIN_SET_JUMP_INTERVAL',
        JUMP_TO: 'MAIN_JUMP_TO',
    },
    FILTERS: {
        COMBINED: 'COMBINED',
        EVENTS: 'EVENTS',
        PLANNING: 'PLANNING',
    },
    PAGE_SIZE: 25,
    PREVIEW: 'preview',
    EDIT: 'edit',
    JUMP: {
        FORWARD: 'FORWARD',
        BACK: 'BACK',
        TODAY: 'TODAY',
        DAY: 'DAY',
        WEEK: 'WEEK',
        MONTH: 'MONTH',
    },
    DATE_RANGE: {
        TODAY: 'today',
        TOMORROW: 'tomorrow',
        THIS_WEEK: 'this_week',
        NEXT_WEEK: 'next_week',
        LAST_24: 'last24'
    }
};
