export const MODALS = {
    CONFIRMATION: 'CONFIRMATION',
    ITEM_ACTIONS_MODAL: 'ITEM_ACTIONS_MODAL',
    NOTIFICATION_MODAL: 'NOTIFICATION_MODAL',
    SORT_SELECTED: 'SORT_SELECTED',
    ADD_TO_PLANNING: 'ADD_TO_PLANNING',
    MANAGE_AGENDAS: 'MANAGE_AGENDAS',
    FULFIL_ASSIGNMENT: 'FULFIL_ASSIGNMENT',
    SELECT_ITEM_MODAL: 'SELECT_ITEM_MODAL',
    EDIT_ITEM: 'EDIT_ITEM',
    IGNORE_CANCEL_SAVE: 'IGNORE_CANCEL_SAVE_MODAL',
};
