export const MODALS = {
    CONFIRMATION: 'CONFIRMATION',
    ITEM_ACTIONS_MODAL: 'ITEM_ACTIONS_MODAL',
    NOTIFICATION_MODAL: 'NOTIFICATION_MODAL',
    SORT_SELECTED: 'SORT_SELECTED',
    ADD_TO_PLANNING: 'ADD_TO_PLANNING',
    EDIT_AGENDA: 'EDIT_AGENDA',
    CREATE_AGENDA: 'CREATE_AGENDA',
    FULFIL_ASSIGNMENT: 'FULFIL_ASSIGNMENT',
}
