export const MULTISELECT = {
    ACTIONS: {
        SELECT_EVENT: 'SELECT_EVENT',
        SELECT_ALL_EVENTS: 'SELECT_ALL_EVENTS',
        DESELECT_EVENT: 'DESELECT_EVENT',
        DESELECT_ALL_EVENTS: 'DESELECT_ALL_EVENTS',
        SELECT_PLANNING: 'SELECT_PLANNING',
        SELECT_ALL_PLANNINGS: 'SELECT_ALL_PLANNINGS',
        DESELECT_PLANNING: 'DESELECT_PLANNING',
        DESELECT_ALL_PLANNINGS: 'DESELECT_ALL_PLANNING',
    }
};
