export const PLANNING = {
    ACTIONS: {
        SPIKE_PLANNING: 'SPIKE_PLANNING',
        UNSPIKE_PLANNING: 'UNSPIKE_PLANNING',
        REQUEST_PLANNINGS: 'REQUEST_PLANNINGS',
        RECEIVE_PLANNINGS: 'RECEIVE_PLANNINGS',
        OPEN_PLANNING_EDITOR: 'OPEN_PLANNING_EDITOR',
        PREVIEW_PLANNING: 'PREVIEW_PLANNING',
        CLOSE_PLANNING_EDITOR: 'CLOSE_PLANNING_EDITOR',
        SET_ONLY_FUTURE: 'SET_ONLY_FUTURE',
        SET_ONLY_SPIKED: 'SET_ONLY_SPIKED',
        PLANNING_FILTER_BY_KEYWORD: 'PLANNING_FILTER_BY_KEYWORD',
        RECEIVE_COVERAGE: 'RECEIVE_COVERAGE',
        COVERAGE_DELETED: 'COVERAGE_DELETED',
    },
}
