export const PRIVILEGES = {
    ARCHIVE: 'archive',
    AGENDA_MANAGEMENT: 'planning_agenda_management',
    DELETE_AGENDA: 'planning_agenda_delete',
    PLANNING_MANAGEMENT: 'planning_planning_management',
    SPIKE_PLANNING: 'planning_planning_spike',
    UNSPIKE_PLANNING: 'planning_planning_unspike',
    EVENT_MANAGEMENT: 'planning_event_management',
    SPIKE_EVENT: 'planning_event_spike',
    UNSPIKE_EVENT: 'planning_event_unspike',
    POST_EVENT: 'planning_event_post',
    UNPOST_EVENT: 'planning_event_unpost',
    POST_PLANNING: 'planning_planning_post',
    UNPOST_PLANNING: 'planning_planning_unpost',
    EDIT_EXPIRED: 'planning_edit_expired',
    CREATE_IN_PAST: 'planning_create_past',
};
