export const TOOLTIPS = {
    spikePlanning: 'Spike planning item',
    unspikePlanning: 'Unspike planning item',
    spikeEvent: 'spikeEventTT',
    unspikeEvent: 'unspikeEventTT',
    editAgenda: 'Edit Agenda',
    edit: 'Edit',
    close: 'Close',
    deleteAgenda: 'Delete Agenda',
    repeatingEvent: 'Repeating Event',
    postedState: 'Posted',
    withheldState: 'The event has been killed',
    scheduledState: 'Scheduled',
    assignmentPriority: {
        1: 'High',
        2: 'Medium',
        3: 'Low',
    },
    notForPublication: 'Not For Publication',
    editModal: 'Edit in popup',
    minimize: 'Minimise',
    actions: 'Actions',
};
