name: "CI-Client"

on: [push, pull_request]

jobs:
  client:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14', '22']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Planning Client (Node 14)
        if: matrix.node-version == '14'
        run: npm ci
      - name: Install Planning Client (Node 22)
        if: matrix.node-version == '22'
        run: npm install
      - run: npm run test
      - run: npm run lint

  extension:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14', '22']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install # needed to support multiple node versions
      - name: install
        working-directory: client/planning-extension
        run: npm ci
      - name: compile
        working-directory: client/planning-extension
        run: npm run compile
