name: "CI-E2E"

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        node-version: ['14', '22']
        e2e: ['a', 'b']
    env:
      INSTALL_NODE_MODULES: false
      RUN_SERVICES: true
      E2E: true
      TZ: Australia/Sydney
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'server/requirements.txt'
      - name: Setup Environment
        run: ./scripts/ci-install.sh
        working-directory: ./
      - name: Install Planning Client
        run: npm ci
        working-directory: ./
      - name: Install E2E Client
        run: npm install
      - name: Build Client
        run: npm run build
      - name: Start Services
        run: ./scripts/ci-start-services.sh
        working-directory: ./
      - name: Start web server
        run: npm run start-client-server

      # playwright start
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: E2E Suite A
        if: matrix.e2e == 'a'
        run: npm run playwright -- --grep events
      - name: E2E Suite B
        if: matrix.e2e == 'b'
        run: npm run playwright -- --grep-invert events
      - uses: actions/upload-artifact@v5
        if: ${{ failure() }}
        with:
          name: playwright-report-${{ matrix.node-version }}-${{ matrix.e2e }}
          path: e2e/test-results
      # playwright end
