name: "CI-E2E"

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
        node-version: ['14']
        e2e: ['a', 'b']
    env:
      INSTALL_NODE_MODULES: true
      RUN_SERVICES: true
      E2E: true
      TZ: Australia/Sydney
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'server/requirements.txt'
      - name: Setup Environment
        run: ./scripts/ci-install.sh
      - name: Build Client
        working-directory: ./e2e
        run: npm run build
      - name: Start Services
        run: ./scripts/ci-start-services.sh
      - name: E2E Suite A
        if: matrix.e2e == 'a'
        working-directory: ./e2e
        run: npm run cypress-ci -- --spec "cypress/integration/events/*.spec.*"
        env:
          CYPRESS_SCREENSHOTS_FOLDER: /tmp/cypress
      - name: E2E Suite B
        if: matrix.e2e == 'b'
        working-directory: ./e2e
        run: npm run cypress-ci -- --spec "cypress/integration/!(events)/*.spec.*"
        env:
          CYPRESS_SCREENSHOTS_FOLDER: /tmp/cypress
      - name: Upload screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots-e2e-${{ matrix.e2e }}
          path: /tmp/cypress/**/*.png
