name: "CI-Server"

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"

jobs:
  server-pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    env:
      INSTALL_PY_MODULES: true
      RUN_SERVICES: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'server/requirements.txt'
      - name: Setup Environment
        run: ./scripts/ci-install.sh
      - name: Start Services
        run: ./scripts/ci-start-services.sh
      - name: Pytest
        run: pytest --log-level=ERROR --disable-warnings server/planning

  server-behave:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    env:
      INSTALL_PY_MODULES: true
      RUN_SERVICES: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'server/requirements.txt'
      - name: Setup Environment
        run: ./scripts/ci-install.sh
      - name: Start Services
        run: ./scripts/ci-start-services.sh
      - name: Behave (Planning Content API)
        working-directory: ./server/
        run: behave --format progress2 --logging-level=ERROR features/planning_content_api
      - name: Behave
        working-directory: ./server
        run: behave --format progress2 --logging-level=ERROR --exclude features/planning_content_api

  prodapi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    env:
      INSTALL_PY_MODULES: true
      INSTALL_PY_EDITABLE: true
      RUN_SERVICES: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'server/requirements.txt'
      - name: Setup Environment
        run: ./scripts/ci-install.sh
      - name: Start Services
        run: ./scripts/ci-start-services.sh
      - name: Pytest
        run: pytest --log-level=ERROR --disable-warnings server/tests/prod_api
